[tool.poetry]
name = "library-management"
version = "0.1.0"
description = ""
authors = ["Árnason, Oddur <oddur.arnason@kpn.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
